[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# delete this in workshop
# solc = "0.8.16"


#delete this in workshop
[etherscan]
bscscan = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config